spring:
  profiles: localtest
  cas:
    sign-out-filters: /logout
    auth-filters: /casLogin
    validate-filters: /casLogin
    request-wrapper-filters: /casLogin
    assertion-filters: /casLogin
    cas-server-login-url: http://221.178.187.38:18080/cas/login
    cas-server-url-prefix: http://221.178.187.38:18080/cas
    redirect-after-validation: true
    use-session: true
    server-name: http://localhost:9004
    
server:
  port: 9099

  